name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKER_TAG_VALUE: $(date +%s)
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ericaclbp/small-alpine-lbp:${DOCKER_TAG_VALUE}
    - name: Push Docker image to registry
      run: docker push ericaclbp/small-alpine-lbp:${DOCKER_TAG_VALUE}
